global:
  message: welcome to Microservices!
logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      
