global:
  message: welcome to prod environment!
spring:
  datasource:
    url: jdbc:mysql://mysql-customer:3306/customerdb_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate,dialect.MySQL8Dialect
    open-in-view: false
