global:
  message: welcome to prod environment!
spring:
  datasource:
    url: jdbc:mysql://mysql-product:3306/productdb_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
