global:
  message: welcome to dev environment!
spring:
  datasource:
    url: jdbc:h2:mem:productdb_dev
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
