global:
  message: welcome to dev environment!
spring:
  datasource:
    url: jdbc:h2:mem:productdb_dev
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    instance-id: ${spring.application.name}:${random.value}

